application/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('register', views.register_user, name='register'),
    path('login', views.login_user, name='login'),
    path('logout_user', views.logout_user, name='logout_user'),
    path('add_category', views.add_category, name='add_category'),
    path('show_categories_and_notes/', views.show_categories_and_notes, name='show_categories_and_notes'),
    path('show_categories_and_notes/<int:category_id>/', views.show_categories_and_notes, name='show_categories_and_notes'),
    path('add_note', views.add_note, name='add_note'),
    path('delete_note/<int:note_id>/', views.delete_note, name='delete_note'),
    path('update_note<int:note_id>', views.update_note, name='update_note'),
    path('delete_category/<int:category_id>/', views.delete_category, name='delete_category'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

finalproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('application.urls'))
]

application/models.py
from django.contrib.auth.models import User
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Note(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to ='uploads/', blank=True,null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.title

application/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.forms import ModelForm
from .models import Category, Note

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Username or Email", widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class CreateCategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = ['name']


class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['title', 'content', 'image', 'category']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(NoteForm, self).__init__(*args, **kwargs)
        if user:
            self.fields['category'].queryset = Category.objects.filter(user=user)

application/views.py
from django.contrib.auth import logout
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_protect
from .forms import RegisterForm, LoginForm, CreateCategoryForm, NoteForm
from django.contrib import messages
from .models import Category, Note
from django.db.models import Q


# Create your views here.
def index(request):
    return render(request, 'base.html')

# User Views

def register_user(request):
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            return redirect('index')
        else:
            messages.error(request, 'An error occurred during registration')

    return render(request, 'register.html', {'form': form})


@csrf_protect
def login_user(request):
    if request.method == 'POST':
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('index')
    else:
        form = LoginForm()
    return render(request, 'login.html', {'form': form})

@login_required(login_url='login')
def logout_user(request):
    logout(request)
    return render(request, 'base.html')


# Category Views


@login_required(login_url='login')
def add_category(request):
    if request.method == 'POST':
        form = CreateCategoryForm(request.POST)
        if form.is_valid():
            category = form.save(commit=False)
            category.user = request.user
            category.save()
            return redirect('show_categories_and_notes')
        return render(request, 'add_category.html', context={'form': form})
    else:
        form = CreateCategoryForm()
    return render(request, 'add_category.html', context={'form': form})


@login_required(login_url='login')
def delete_category(request, category_id):
    category = Category.objects.get(id=category_id)
    notes = Note.objects.filter(category=category)
    notes.delete()
    category.delete()
    return redirect('show_categories_and_notes')

@login_required
def show_categories_and_notes(request, category_id=None):
    search_query = request.GET.get('search')
    categories = Category.objects.filter(user=request.user).all()
    notes = Note.objects.filter(user=request.user, category__isnull=False).all()
    if category_id:
        try:
            category = Category.objects.get(id=category_id)
            notes = notes.filter(category=category)
        except Category.DoesNotExist:
            pass
    if search_query:
        notes = notes.filter(Q(title__icontains=search_query) | Q(content__icontains=search_query))
    user_notes = Note.objects.filter(user=request.user, category=None)
    return render(request, 'categories_and_notes.html', {'notes': notes, 'category_id': category_id, 'categories': categories, 'user_notes': user_notes, 'search_query': search_query})


# Note Views

@login_required(login_url='login')
def update_note(request, note_id):
    note = get_object_or_404(Note, pk=note_id)
    categories = Category.objects.filter(user=request.user)
    if request.method == 'POST':
        note.title = request.POST['title']
        note.content = request.POST['content']
        note.category_id = request.POST['category']
        if 'image' in request.FILES:
            note.image = request.FILES['image']
        note.save()
        return redirect('show_categories_and_notes')

    return render(request, 'update_note.html', {'note': note, 'categories':categories})


@login_required(login_url='login')
def add_note(request):
    if request.method == 'POST':
        form = NoteForm(request.POST, request.FILES, user=request.user)
        if form.is_valid():
            note = form.save(commit=False)
            note.user = request.user
            note.save()
            return redirect('show_categories_and_notes')
    else:
        form = NoteForm(user=request.user)
    return render(request, 'add_note.html', {'form': form})



@login_required(login_url='login')
def delete_note(request, note_id):
    note = Note.objects.get(id=note_id)
    note.delete()
    return redirect('show_categories_and_notes')

application/templates/add_category.html
{% extends 'base.html' %}

{% block content %}
<style>

    .form-group {
        background-color: #333;
        color: #fff;
    }
    .form-control {
        background-color: #444;
        color: #fff;
    }
    .btn-primary {
        background-color: #007bff;
        border-color: #007bff;
        color: #fff;
    }
     .btn-create {
           display: inline-block;
            font-weight: 400;
            line-height: 1.5;
            color: #212529;
            text-align: center;
            text-decoration: none;
            vertical-align: middle;
            cursor: pointer;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
            border: 1px solid transparent;
            padding: .375rem .75rem;
            font-size: 1rem;
            border-radius: .25rem;
            background-color: #FFFFFF;
    }

</style>
<div class="container mt-5">
  <h1 class="text-center mb-4" style="color: #ffff">Create Category</h1>
  <form method="post">
    {% csrf_token %}
    <div class="form-group">
      {{ form.as_p }}
    </div>
    <input type="submit" class="btn-create" value="Create">
  </form>
</div>
{% endblock %}

application/templates/add_note.html
{% extends 'base.html' %}

{% block content %}
<style>
  .form-group {
  padding: 10px;
  }
</style>
<div class="container mt-5" style="background-color: #282828; color: #f2f2f2;">
  <h1 class="text-center mb-4">Create Note</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group" style="background-color: #3e3e3e;">
      <label for="title" style="color: #f2f2f2;">Title:</label>
      <input type="text" name="title" id="title" class="form-control" style="background-color: #3e3e3e; color: #f2f2f2;">
    </div>
    <div class="form-group" style="background-color: #3e3e3e;">
      <label for="content" style="color: #f2f2f2;">Content:</label>
      <textarea name="content" id="content" class="form-control" style="background-color: #3e3e3e; color: #f2f2f2;"></textarea>
    </div>
    <div class="form-group" style="background-color: #3e3e3e;">
      <label for="category" style="color: #f2f2f2;">Category:</label>
      <select name="category" id="category" class="form-control" style="background-color: #3e3e3e; color: #f2f2f2;">
        <option value="">--Select Category--</option>
        {% for category in user.category_set.all %}
        <option value="{{ category.id }}" style="color: #f2f2f2;">{{ category.name }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="form-group" style="background-color: #3e3e3e;">
      <label for="image" style="color: #f2f2f2;">Image:</label>
      <input type="file" name="image" id="image" class="form-control" style="background-color: #3e3e3e; color: #f2f2f2;">
    </div>
    <input type="submit" class="btn btn-primary" value="Create" style="background-color: #f2f2f2; color: #282828;">
  </form>
</div>
{% endblock %}

application/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
   <style>
        .navbar-brand, .navbar-nav .nav-link {
            color: #dadce0 !important
        }

        body {
            background-color: #333;
        }
        .navbar {
            background-color: #333;

        }
        .navbar-brand {
            color: #fff;
        }
        .navbar-nav .nav-link {
            color: #fff;
        }

    </style>
    <title>My Website</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand" href="#">My Website</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            {% if user.is_authenticated %}

            <li class="nav-item">
              <a class="nav-link" href="{% url 'show_categories_and_notes' %}">Show Categories</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout_user' %}">Logout</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="#">Welcome, {{ user.username }}</a>
            </li>
        </ul>
    </div>
</nav>
{%else %}
<ul class="navbar-nav">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'register' %}">Register</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Login</a>
    </li>
</ul>
{% endif %}

{% block content %}


{% endblock %}


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.16.0/dist/umd/popper.min.js"
        integrity="sha384-uZmjT6k8bV7w/wZr0kVU2vYdO7M5o9sUZT6+ZpzFo7VxwK1xZrLrO/1yEjRUJ9X"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
        crossorigin="anonymous"></script>
</body>
</html>

application/templates/categories_and_notes.html
{% extends 'base.html' %}

{% block content %}
<style>
    form {
    padding-bottom: 20px;
    }
    .card {
        background-color: #333;
        color: #fff;
    }
    .card-header {
        background-color: #333;
    }
    .card-title {
        color: #dadce0;
    }
    .card-text {
        color: #dadce0;
    }
    .card-body {
        background-color: #444;
    }
    .btn-danger {
        background-color: #dc3545;
        border-color: #dc3545;
        color: #fff;
    }
    .btn-primary {
        background-color: #007bff;
        border-color: #007bff;
        color: #fff;
    }
    .btn-note, .btn-category{
        text-decoration: none;
        color: #dadce0;
        font-family: "Google Sans",Roboto,Arial,sans-serif;
        font-size: .875rem;
        font-weight: 500;
        line-height: 1.25rem;
        height: 36px;
        padding: 8px 24px;
        border-radius: 4px;
        cursor: pointer;
        background-color: #444;
    }

    .btn-update {
           display: inline-block;
            font-weight: 400;
            color: #212529;
            text-decoration: none;
            vertical-align: middle;
            cursor: pointer;
            user-select: none;
            border: 1px solid transparent;
            padding: .375rem .75rem;
            font-size: 1rem;
            border-radius: .25rem;
            background-color: #FFFFFF;
    }

</style>

<form action="{% url 'show_categories_and_notes' %}" method="get">
    <input type="text" name="search" id="search" style="margin-left: 13px;"  >
    <input type="submit" value="Search" >
    <a href="{% url 'add_note' %}" class="btn-note">Add Note</a>
    <a href="{% url 'add_category' %}" class="btn-category">Add Category</a>
</form>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">Categories:</h5>
                </div>
                <div class="card-body">
                    <div class="list-group">
                        <a href="{% url 'show_categories_and_notes' %}" class="list-group-item list-group-item-action">All
                            Categories</a>
                        {% for category in categories %}
                        <div class="list-group-item d-flex justify-content-between align-items-center">
                            <a href="{% url 'show_categories_and_notes' category.id %}">{{ category.name }}</a>
                            <a href="{% url 'delete_category' category.id %}"  class="btn btn-danger btn-sm"
                                   onclick="return confirm('Are you sure you want to delete this Category?');">Delete</a>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-9">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">Notes:</h5>
                </div>
                <div class="card-body">
                    <div class="card-text">
                        <div class="row">
                            <div class="col-md-6">
                                <h6>Notes with category:</h6>
                                {% for note in notes %}
                                <p>Title: {{ note.title }} ({{ note.category.name }})</p>
                                <p>{{ note.content }}</p>
                                <p class="text-muted">Created: {{ note.created_at|timesince }} ago</p>
                                <p class="text-muted">Updated: {{ note.updated_at|timesince }} ago</p>
                                {% if note.image %}
                                <img class="img-thumbnail" src="{{ note.image.url }}" alt="{{ note.title }}"
                                     height="150" width="100">
                                {% endif %}
                                <a href="{% url 'update_note' note.id %}" class="btn-update">Update</a>
                                <a href="{% url 'delete_note' note.id %}" class="btn btn-danger"
                                   onclick="return confirm('Are you sure you want to delete this note?');">Delete</a>
                                {% endfor %}
                            </div>
                            <div class="col-md-6">
                                {% if category_id is None %}
                                <h6>Notes without category:</h6>
                                {% for note in user_notes %}
                                <p>{{ note.title }}</p>
                                <p>{{ note.content }}</p>
                                <p class="text-muted">Created: {{ note.created_at|timesince }} ago</p>
                                <p class="text-muted">Updated: {{ note.updated_at|timesince }} ago</p>
                                {% if note.image %}
                                <img class="img-thumbnail" src="{{ note.image.url }}" alt="{{ note.title }}"
                                     height="150" width="100">
                                {% endif %}
                                <a href="{% url 'update_note' note.id %}" class="btn-update">Update</a>
                                <a href="{% url 'delete_note' note.id %}" class="btn btn-danger"
                                   onclick="return confirm('Are you sure you want to delete this note?');">Delete</a>
                                {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

application/templates/index.html
{% extends 'base.html' %}

{% block content %}

{% endblock %}

application/templates/login.html
{% extends 'base.html' %}

{% block content %}
<style>
    .card {
    background-color: #333;
    color: #fff;
}
.card-header {
    background-color: #333;
    color: #fff;
}
.card-body {
    background-color: #333;
}
.form-control {
    background-color: #444;
    color: #fff;
    border-color: #fff;
}
.btn-primary {
    background-color: #555;
    color: #fff;
    border-color: #fff;
}
</style>

<div class="d-flex justify-content-center align-items-center" style="height:100vh">
    <div class="card bg-black">
        <div class="card-header text-center text-white">
            <h4>Login</h4>
        </div>
        <div class="card-body text-white">
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.username.id_for_label }}">Username</label>
                    <input type="text" name="username" id="{{ form.username.id_for_label }}" class="form-control" style="color: #000">
                    {% if form.username.errors %}
                      <div class="text-danger">
                        {{ form.username.errors }}
                      </div>
                    {% endif %}
                </div>
                <div class="form-group">
                    <label for="{{ form.password.id_for_label }}">Password</label>
                    <input type="password" name="password" id="{{ form.password.id_for_label }}" class="form-control" >
                    {% if form.password.errors %}
                      <div class="text-danger">
                        {{ form.password.errors }}
                      </div>
                    {% endif %}
                </div>
                <div class="form-group text-center">
                    <input type="submit" value="Login" class="btn btn-primary text-black">
                </div>
                <div class="form-group text-center">
                    <a href="{% url 'register' %}" class="btn btn-secondary text-black">Don't have an account? Sign Up</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

application/templates/register.html
{% extends 'base.html' %}

{% block content %}
<style>
    .card {
    background-color: #333;
    color: #fff;
}
.card-header {
    background-color: #333;
    color: #fff;
}
.card-body {
    background-color: #333;
}
.form-control {
    background-color: #444;
    color: #fff;
    border-color: #fff;
}
.btn-primary {
    background-color: #555;
    color: #fff;
    border-color: #fff;
}
</style>

<div class="d-flex justify-content-center align-items-center" style="height:100vh">
    <div class="card bg-black text-white">
        <div class="card-header text-center">
            <h4>Register</h4>
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.username.id_for_label }}">Username</label>
                    <input type="text" name="username" id="{{ form.username.id_for_label }}" class="form-control" style="color: #000">
                    {% if form.username.errors %}
                    <div class="text-danger">
                        {{ form.username.errors }}
                    </div>
                    {% endif %}
                </div>
                <div class="form-group">
                    <label for="{{ form.email.id_for_label }}">Email</label>
                    <input type="email" name="email" id="{{ form.email.id_for_label }}" class="form-control" style="color: #000">
                    {% if form.email.errors %}
                    <div class="text-danger">
                        {{ form.email.errors }}
                    </div>
                    {% endif %}
                </div>
                <div class="form-group">
                    <label for="{{ form.password1.id_for_label }}">Password</label>
                    <input type="password" name="password1" id="{{ form.password1.id_for_label }}" class="form-control" style="color: #000">
                    {% if form.password1.errors %}
                    <div class="text-danger">
                        {{ form.password1.errors }}
                    </div>
                    {% endif %}
                </div>
                <div class="form-group">
                    <label for="{{ form.password2.id_for_label }}">Confirm Password</label>
                    <input type="password" name="password2" id="{{ form.password2.id_for_label }}" class="form-control" style="color: #000">
                    {% if form.password2.errors %}
                    <div class="text-danger">
                        {{ form.password2.errors }}
                    </div>
                    {% endif %}
                </div>
                <div class="form-group text-center">
                    <input type="submit" value="Sign up" class="btn btn-primary text-black">
                </div>
                <div class="form-group text-center">
                    <a href="{% url 'login' %}" class="btn btn-secondary text-white">Already have an account? Sign in</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

application/templates/update_note.html
{% extends 'base.html' %}

{% block content %}
<style>
  .container{
  color: #FFFFFF;
 }
 .btn-update {
           display: inline-block;
            font-weight: 400;
            line-height: 1.5;
            color: #212529;
            text-align: center;
            text-decoration: none;
            vertical-align: middle;
            cursor: pointer;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
            border: 1px solid transparent;
            padding: .375rem .75rem;
            font-size: 1rem;
            border-radius: .25rem;
            background-color: #FFFFFF;
            margin-top: 15px;
    }

</style>
<div class="container">
  <h2 class="text-center">Update Note</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
      <label for="title">Title</label>
      <input type="text" class="form-control" id="title" name="title" value="{{ note.title }}">
    </div>
    <div class="form-group">
      <label for="content">Content</label>
      <textarea class="form-control" id="content" name="content" rows="3">{{ note.content }}</textarea>
    </div>
    <div class="form-group" style="padding-top: 10px">
      <label for="image">Image</label>
      <input type="file" class="form-control-file" id="image" name="image">
      {% if note.image %}
        <img class="img-thumbnail" src="{{ note.image.url }}" alt="{{ note.title }}" height="150" width="100">
      {% endif %}
    </div>
    <div class="form-group">
  <label for="category">Category</label>
  <select class="form-control" id="category" name="category">
    <option value="" selected>Select a category</option>
    {% for category in categories %}
    <option value="{{ category.id }}" >{{ category.name }}</option>
    {% endfor %}
  </select>
</div>
    <button type="submit" class="btn-update">Update</button>
  </form>
</div>
{% endblock content %}